name: Automated Testing (Unit & Integration)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    permissions : 
      contents : write

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' 
        extensions: mysqli, mbstring, xml
        tools: composer:v2
       
        coverage: xdebug 

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Wait for MySQL to be Ready
      run: |
        until mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
          echo "Waiting for MySQL database..."
          sleep 2
        done

    - name: Import Database Schema
      run: |
        mysql -h 127.0.0.1 -u root -proot db_testing < database/schema.sql

    # --- TAHAP PENGUJIAN & COVERAGE ---
    
    - name: Run Unit Tests
      run: vendor/bin/phpunit --testsuite Unit --coverage-text

    - name: Run Integration Tests
      run: |
        # TAMBAHKAN flag --coverage-clover coverage.xml di sini
        vendor/bin/phpunit --testsuite Integration --coverage-text --coverage-clover coverage.xml --coverage-html tests/coverage-html
      env:
        DB_HOST: 127.0.0.1
        DB_NAME: db_testing
        DB_USER: root
        DB_PASS: root

    - name: Upload Coverage Report
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: phpunit-coverage-report
        path: tests/coverage-html/

    - name: Generate Coverage Badge
      uses: stevenalexander/phpunit-coverage-badge@v1.1.0
      with:
        report: coverage.xml 
        target: badges/coverage.svg